config/routes.rb
Rails.application.routes.draw do

  resources :boards
  

  root to: 'boards#index'

  

end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :lists
  has_many :items, through: :lists

  validates_presence_of :name

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list

  validates_presence_of :name
end

app/models/list.rb
class List < ActiveRecord::Base

  belongs_to :board
  has_many   :items

  validates_presence_of :name

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  def index
    @boards = Board.all
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)
    @board.save

    redirect_to @board
  end



  def show
    @board = Board.find(params[:id])
  end

  def edit
    @board = Board.find(params[:id])
  end

  def update
    @board = Board.find(params[:id])
    @board.update(board_params)
    @board.save

    redirect_to @board
  end

  def destroy
    @board = Board.find(params[:id])
    @board.destroy
  end

  private
    def board_params
      params.require(:board).permit(:name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/destroy.js.erb
$("#li-<%= @board.id %>").remove();

app/views/boards/index.html.erb
<h1>My Boards</h1><br>

<div class="new-board-form">
  <h2>Create New Board</h2>
    <%= form_for @board do |f| %>
      <%= f.text_field :name, id: 'new-todo', placeholder: 'e.g., Projects, etc.' %>
      <%= f.submit %>
      <% end %>
</div>

<div class="all-boards-list">
  <ul id="all-boards-list">
    <h2>
      <% @boards.each do |board| %>
          <li id="li-<%= board.id %>"><%= link_to "#{board.name}", board_path(board) %>   <%= button_to "x", board_path(board), method: "delete", remote: true %></li>
      <% end %>
    </h2>
  </ul>
</div>

app/views/boards/show.html.erb
<h1><%= @board.name %></h1>

<% @board.lists.each do |l| %>
  <header>
    <h1><%= l.name %></h1>
  </header>
<% end %>

<%= link_to "Return to My Boards", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>